### ISSUE TITLE
Hasn't watched Node.js since 2/16/15

### ISSUE THREAD

**Issue by corysimmons** [piscisaureus/slurp#4]

**Comment by joepie91** [comment]
Further clarification: logs at logs.nodejs.org haven't been updated since that date, and the bot doesn't seem to be connected to Freenode anymore at all.

**Comment by piscisaureus** [comment]
Ah, I'm sorry. 
The bot was partially working (#libuv and #io.js were still being logged) so I didn't notice it had disconnected from freenode.

I've restarted the log bot. If you notice it going down again please let me know.
